
import "./globals.css";
import Navbar from "./navbar/page";


export const metadata = {
  title: "Omni Share",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" webcrx="">
      <body>
        <div className="flex absolute z-0 ">
              <img src="/background.jpg" alt="" srcset="" className="h-fit w-fit "/>
          </div>
          <div className="z-10 relative ">
            <Navbar/>
            {children}
          </div>
      </body>
    </html>
  );
}
